[tool.poetry]
name = "bbpb"
version = "0.1.1"
description = "Library for working with protobuf messages without a protobuf type definition."
authors = ["Ryan Winkelmaier <ryan.winkelmaier@nccgroup.com>"]
license = "MIT"
repository = "https://github.com/nccgroup/blackboxprotobuf"
readme = "README.md"
keywords = ["protobuf"]
exclude = ["/tests"]

[tool.poetry.dependencies]
python = "^2.7 || ^3.3"
protobuf = [ { version = "^3", python = "^3" },
             { version = "3.17.3", python = "^2.7" } ]
six = "^1.16"


[tool.poetry.dev-dependencies]
pytest = [ { version = "^6", python = "^3.5" },
           { version = "4.6.11", python = "^2.7" } ]
# missing pytest dependency
more_itertools = { version = "^5.0", python = "^2.7" }
hypothesis = [ { version = "^6", python = "^3.6" },
               { version = "4.57.1", python = "^2.7" } ]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
