# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ResTextClient.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13ResTextClient.proto\x12\x15\x63om.tencent.nk.xlsRes\"\xc6\x04\n\x0e\x43lientTextInfo\x12\x10\n\x03key\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x12\n\x05zh_CN\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x12\n\x05zh_GL\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x12\n\x05zh_TW\x18\x04 \x01(\tH\x03\x88\x01\x01\x12\x12\n\x05\x65n_US\x18\x05 \x01(\tH\x04\x88\x01\x01\x12\x12\n\x05ja_JP\x18\x06 \x01(\tH\x05\x88\x01\x01\x12\x12\n\x05ko_KR\x18\x07 \x01(\tH\x06\x88\x01\x01\x12\x12\n\x05\x64\x65_DE\x18\x08 \x01(\tH\x07\x88\x01\x01\x12\x12\n\x05\x66r_FR\x18\t \x01(\tH\x08\x88\x01\x01\x12\x12\n\x05\x65s_ES\x18\n \x01(\tH\t\x88\x01\x01\x12\x12\n\x05it_IT\x18\x0b \x01(\tH\n\x88\x01\x01\x12\x12\n\x05ru_RU\x18\x0c \x01(\tH\x0b\x88\x01\x01\x12\x12\n\x05\x61r_AR\x18\r \x01(\tH\x0c\x88\x01\x01\x12\x12\n\x05tr_TR\x18\x0e \x01(\tH\r\x88\x01\x01\x12\x12\n\x05th_TH\x18\x0f \x01(\tH\x0e\x88\x01\x01\x12\x12\n\x05ms_MY\x18\x10 \x01(\tH\x0f\x88\x01\x01\x12\x12\n\x05id_ID\x18\x11 \x01(\tH\x10\x88\x01\x01\x12\x12\n\x05vi_VN\x18\x12 \x01(\tH\x11\x88\x01\x01\x12\x12\n\x05pt_PT\x18\x13 \x01(\tH\x12\x88\x01\x01\x42\x06\n\x04_keyB\x08\n\x06_zh_CNB\x08\n\x06_zh_GLB\x08\n\x06_zh_TWB\x08\n\x06_en_USB\x08\n\x06_ja_JPB\x08\n\x06_ko_KRB\x08\n\x06_de_DEB\x08\n\x06_fr_FRB\x08\n\x06_es_ESB\x08\n\x06_it_ITB\x08\n\x06_ru_RUB\x08\n\x06_ar_ARB\x08\n\x06_tr_TRB\x08\n\x06_th_THB\x08\n\x06_ms_MYB\x08\n\x06_id_IDB\x08\n\x06_vi_VNB\x08\n\x06_pt_PT\"K\n\x14table_ClientTextInfo\x12\x33\n\x04rows\x18\x01 \x03(\x0b\x32%.com.tencent.nk.xlsRes.ClientTextInfob\x06proto3')



_CLIENTTEXTINFO = DESCRIPTOR.message_types_by_name['ClientTextInfo']
_TABLE_CLIENTTEXTINFO = DESCRIPTOR.message_types_by_name['table_ClientTextInfo']
ClientTextInfo = _reflection.GeneratedProtocolMessageType('ClientTextInfo', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTTEXTINFO,
  '__module__' : 'ResTextClient_pb2'
  # @@protoc_insertion_point(class_scope:com.tencent.nk.xlsRes.ClientTextInfo)
  })
_sym_db.RegisterMessage(ClientTextInfo)

table_ClientTextInfo = _reflection.GeneratedProtocolMessageType('table_ClientTextInfo', (_message.Message,), {
  'DESCRIPTOR' : _TABLE_CLIENTTEXTINFO,
  '__module__' : 'ResTextClient_pb2'
  # @@protoc_insertion_point(class_scope:com.tencent.nk.xlsRes.table_ClientTextInfo)
  })
_sym_db.RegisterMessage(table_ClientTextInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CLIENTTEXTINFO._serialized_start=47
  _CLIENTTEXTINFO._serialized_end=629
  _TABLE_CLIENTTEXTINFO._serialized_start=631
  _TABLE_CLIENTTEXTINFO._serialized_end=706
# @@protoc_insertion_point(module_scope)
